# This config file contains the list of patches
# to be applied by callisto during the build

# You can remove or comment out (append a # to the line)
# from this file to "remove" a patch since it will be
# omitted during next build

[resources]
# The "patches_folder" is defined in variables.toml
patches = [
    "{patches_folder}/consistency/capespin_direction_toggleable.asm",
    "{patches_folder}/consistency/capespin_net_hitbox.asm",
    "{patches_folder}/consistency/item_release_bulk.asm",
    "{patches_folder}/enhancements/bullet_bill_sfx_extra_bit.asm",
    "{patches_folder}/enhancements/charles_remembers.asm",
    "{patches_folder}/enhancements/double_bounce_palette.asm",
    "{patches_folder}/enhancements/exit-enabled_growing_pipe_extra_bit.asm",
    "{patches_folder}/enhancements/fix_piranhas_red_stem_extra_bit.asm",
    "{patches_folder}/enhancements/placeable_disco_shell.asm",
    "{patches_folder}/enhancements/placeable_kicked_shell.asm",
    "{patches_folder}/enhancements/placeable_throw_block.asm",
    "{patches_folder}/enhancements/poison_mushroom.asm",
    "{patches_folder}/enhancements/spiketop_ceiling_fix.asm",
    "{patches_folder}/enhancements/sprite_submap_behaviour_extra_bit.asm",
    "{patches_folder}/enhancements/squished_rex_extra_bit.asm",
    "{patches_folder}/enhancements/triple_ball_n_chain.asm",
    "{patches_folder}/features/dragon_coin_save.asm",
    "{patches_folder}/features/ram_toggled_screen_scroll.asm",
    "{patches_folder}/features/ram_toggled_spin_jump_fireballs.asm",
    "{patches_folder}/features/ram_toggled_statusbar.asm",
    "{patches_folder}/fixes/autoscroll_lr_fix.asm",
    "{patches_folder}/fixes/ball_chain_yoshi_fix.asm",
    "{patches_folder}/fixes/block_duplication_fix_toggleable.asm",
    "{patches_folder}/fixes/block_snake_fix.asm",
    "{patches_folder}/fixes/bomb_palette_fix.asm",
    "{patches_folder}/fixes/bounce_block_death_fix.asm",
    "{patches_folder}/fixes/bowser_fire_despawn_fix.asm",
    "{patches_folder}/fixes/candle_flames_fix.asm",
    "{patches_folder}/fixes/capespin_hitbox_position_fix.asm",
    "{patches_folder}/fixes/castle_block_fix.asm",
    "{patches_folder}/fixes/castle_ledge_fix.asm",
    "{patches_folder}/fixes/cluster_boo_ducking_fix.asm",
    "{patches_folder}/fixes/dark_room_background_fix.asm",
    "{patches_folder}/fixes/dead_spring_fix.asm",
    "{patches_folder}/fixes/double_spin_fix.asm",
    "{patches_folder}/fixes/feather_during_autoscroll_fix.asm",
    "{patches_folder}/fixes/fire_berry_fix.asm",
    "{patches_folder}/fixes/goal_point_reward_fix.asm",
    "{patches_folder}/fixes/hammer_bro_fix.asm",
    "{patches_folder}/fixes/horizontal_scroll_fix.asm",
    "{patches_folder}/fixes/layer2+3_triangles_fix.asm",
    "{patches_folder}/fixes/line_guide_actas_fix.asm",
    "{patches_folder}/fixes/line_rope_length_fix.asm",
    "{patches_folder}/fixes/net_screen_boundary_fix.asm",
    "{patches_folder}/fixes/no_jump_at_high_speed_fix.asm",
    "{patches_folder}/fixes/no_sprite_interaction_fix.asm",
    "{patches_folder}/fixes/p-balloon_cloud_fix.asm",
    "{patches_folder}/fixes/player_pose_fix.asm",
    "{patches_folder}/fixes/power_up_priority_fix.asm",
    "{patches_folder}/fixes/pressed_switch_yoshi_fix.asm",
    "{patches_folder}/fixes/proximity_wrap_fix.asm",
    "{patches_folder}/fixes/question_block_collision_fix.asm",
    "{patches_folder}/fixes/rollover_fix.asm",
    "{patches_folder}/fixes/rope_fixes_toggleable.asm",
    "{patches_folder}/fixes/skull_raft_fix.asm",
    "{patches_folder}/fixes/slide_kill_gfx_fix.asm",
    "{patches_folder}/fixes/speed_oscillation_fix.asm",
    "{patches_folder}/fixes/spike_swim_fix.asm",
    "{patches_folder}/fixes/springboard_fixes_toggleable.asm",
    "{patches_folder}/fixes/sprite_ceiling_fix.asm",
    "{patches_folder}/fixes/sprite_scroll_fix.asm",
    "{patches_folder}/fixes/tide_current_fix.asm",
    "{patches_folder}/fixes/time_up_fix.asm",
    "{patches_folder}/fixes/titlescreen_sprite_cleaner.asm",
    "{patches_folder}/fixes/torpedo_offscreen_smoke_fix.asm",
    "{patches_folder}/fixes/triple_rotating_platform_vertical_level_fix.asm",
    "{patches_folder}/fixes/vertical_despawn_fix.asm",
    "{patches_folder}/fixes/wall_jump_noteblock_clipping_fix.asm",
    "{patches_folder}/fixes/yoshi_pipe_animation_fix.asm",
    "{patches_folder}/fixes/screen_scrolling_pipes_fixes.asm",
    "{patches_folder}/objectool/objectool.asm",
    "{patches_folder}/optimizations/fixed_color_data_nmi_optimize.asm",
    "{patches_folder}/optimizations/layer2_buoyancy_optimize.asm",
    "{patches_folder}/optimizations/optimize_1f0.asm",
    "{patches_folder}/optimizations/optimize_statusbar_nmi.asm",
    "{patches_folder}/optimizations/vram_optimize.asm",
    "{patches_folder}/other/extended_no_more_sprite_tile_limits.asm",
    "{patches_folder}/other/free_tile_69.asm",
    "{patches_folder}/other/free_up_ram.asm",
    "{patches_folder}/other/mario_gfx_dma.asm",
    "{patches_folder}/other/no_more_sprite_tile_limits.asm",
    "{patches_folder}/other/puff_of_smoke_sprite.asm",
    "{patches_folder}/sprite_remaps.asm",
    "{patches_folder}/tweaks.asm",
]