
# Project variables
[variables]

     # Feel free to change this!
    project_name = "RHRv5"

    # Don't change this (unless you move all the patches)
    patches_folder = "resources/patches"
    tools_folder = "tools"
