
# Project variables
[variables]

     # Feel free to change this!
    project_name = "RHRv5"

    # Don't change these folder definitions unless you know what you are doing
    export_folder        = "export"
    resources_folder     = "resources"
    patches_folder       = "{resources_folder}/patches"
    tools_folder         = "tools"
    shared_folder        = "shared"
    output_folder        = "workspace"
