LevelResourcePointers:
    dw Level0JSLs
    dw Level1JSLs
    dw Level2JSLs
    dw Level3JSLs
    dw Level4JSLs
    dw Level5JSLs
    dw Level6JSLs
    dw Level7JSLs
    dw Level8JSLs
    dw Level9JSLs
    dw LevelAJSLs
    dw LevelBJSLs
    dw LevelCJSLs
    dw LevelDJSLs
    dw LevelEJSLs
    dw LevelFJSLs
    dw Level10JSLs
    dw Level11JSLs
    dw Level12JSLs
    dw Level13JSLs
    dw Level14JSLs
    dw Level15JSLs
    dw Level16JSLs
    dw Level17JSLs
    dw Level18JSLs
    dw Level19JSLs
    dw Level1AJSLs
    dw Level1BJSLs
    dw Level1CJSLs
    dw Level1DJSLs
    dw Level1EJSLs
    dw Level1FJSLs
    dw Level20JSLs
    dw Level21JSLs
    dw Level22JSLs
    dw Level23JSLs
    dw Level24JSLs
    dw Level25JSLs
    dw Level26JSLs
    dw Level27JSLs
    dw Level28JSLs
    dw Level29JSLs
    dw Level2AJSLs
    dw Level2BJSLs
    dw Level2CJSLs
    dw Level2DJSLs
    dw Level2EJSLs
    dw Level2FJSLs
    dw Level30JSLs
    dw Level31JSLs
    dw Level32JSLs
    dw Level33JSLs
    dw Level34JSLs
    dw Level35JSLs
    dw Level36JSLs
    dw Level37JSLs
    dw Level38JSLs
    dw Level39JSLs
    dw Level3AJSLs
    dw Level3BJSLs
    dw Level3CJSLs
    dw Level3DJSLs
    dw Level3EJSLs
    dw Level3FJSLs
    dw Level40JSLs
    dw Level41JSLs
    dw Level42JSLs
    dw Level43JSLs
    dw Level44JSLs
    dw Level45JSLs
    dw Level46JSLs
    dw Level47JSLs
    dw Level48JSLs
    dw Level49JSLs
    dw Level4AJSLs
    dw Level4BJSLs
    dw Level4CJSLs
    dw Level4DJSLs
    dw Level4EJSLs
    dw Level4FJSLs
    dw Level50JSLs
    dw Level51JSLs
    dw Level52JSLs
    dw Level53JSLs
    dw Level54JSLs
    dw Level55JSLs
    dw Level56JSLs
    dw Level57JSLs
    dw Level58JSLs
    dw Level59JSLs
    dw Level5AJSLs
    dw Level5BJSLs
    dw Level5CJSLs
    dw Level5DJSLs
    dw Level5EJSLs
    dw Level5FJSLs
    dw Level60JSLs
    dw Level61JSLs
    dw Level62JSLs
    dw Level63JSLs
    dw Level64JSLs
    dw Level65JSLs
    dw Level66JSLs
    dw Level67JSLs
    dw Level68JSLs
    dw Level69JSLs
    dw Level6AJSLs
    dw Level6BJSLs
    dw Level6CJSLs
    dw Level6DJSLs
    dw Level6EJSLs
    dw Level6FJSLs
    dw Level70JSLs
    dw Level71JSLs
    dw Level72JSLs
    dw Level73JSLs
    dw Level74JSLs
    dw Level75JSLs
    dw Level76JSLs
    dw Level77JSLs
    dw Level78JSLs
    dw Level79JSLs
    dw Level7AJSLs
    dw Level7BJSLs
    dw Level7CJSLs
    dw Level7DJSLs
    dw Level7EJSLs
    dw Level7FJSLs
    dw Level80JSLs
    dw Level81JSLs
    dw Level82JSLs
    dw Level83JSLs
    dw Level84JSLs
    dw Level85JSLs
    dw Level86JSLs
    dw Level87JSLs
    dw Level88JSLs
    dw Level89JSLs
    dw Level8AJSLs
    dw Level8BJSLs
    dw Level8CJSLs
    dw Level8DJSLs
    dw Level8EJSLs
    dw Level8FJSLs
    dw Level90JSLs
    dw Level91JSLs
    dw Level92JSLs
    dw Level93JSLs
    dw Level94JSLs
    dw Level95JSLs
    dw Level96JSLs
    dw Level97JSLs
    dw Level98JSLs
    dw Level99JSLs
    dw Level9AJSLs
    dw Level9BJSLs
    dw Level9CJSLs
    dw Level9DJSLs
    dw Level9EJSLs
    dw Level9FJSLs
    dw LevelA0JSLs
    dw LevelA1JSLs
    dw LevelA2JSLs
    dw LevelA3JSLs
    dw LevelA4JSLs
    dw LevelA5JSLs
    dw LevelA6JSLs
    dw LevelA7JSLs
    dw LevelA8JSLs
    dw LevelA9JSLs
    dw LevelAAJSLs
    dw LevelABJSLs
    dw LevelACJSLs
    dw LevelADJSLs
    dw LevelAEJSLs
    dw LevelAFJSLs
    dw LevelB0JSLs
    dw LevelB1JSLs
    dw LevelB2JSLs
    dw LevelB3JSLs
    dw LevelB4JSLs
    dw LevelB5JSLs
    dw LevelB6JSLs
    dw LevelB7JSLs
    dw LevelB8JSLs
    dw LevelB9JSLs
    dw LevelBAJSLs
    dw LevelBBJSLs
    dw LevelBCJSLs
    dw LevelBDJSLs
    dw LevelBEJSLs
    dw LevelBFJSLs
    dw LevelC0JSLs
    dw LevelC1JSLs
    dw LevelC2JSLs
    dw LevelC3JSLs
    dw LevelC4JSLs
    dw LevelC5JSLs
    dw LevelC6JSLs
    dw LevelC7JSLs
    dw LevelC8JSLs
    dw LevelC9JSLs
    dw LevelCAJSLs
    dw LevelCBJSLs
    dw LevelCCJSLs
    dw LevelCDJSLs
    dw LevelCEJSLs
    dw LevelCFJSLs
    dw LevelD0JSLs
    dw LevelD1JSLs
    dw LevelD2JSLs
    dw LevelD3JSLs
    dw LevelD4JSLs
    dw LevelD5JSLs
    dw LevelD6JSLs
    dw LevelD7JSLs
    dw LevelD8JSLs
    dw LevelD9JSLs
    dw LevelDAJSLs
    dw LevelDBJSLs
    dw LevelDCJSLs
    dw LevelDDJSLs
    dw LevelDEJSLs
    dw LevelDFJSLs
    dw LevelE0JSLs
    dw LevelE1JSLs
    dw LevelE2JSLs
    dw LevelE3JSLs
    dw LevelE4JSLs
    dw LevelE5JSLs
    dw LevelE6JSLs
    dw LevelE7JSLs
    dw LevelE8JSLs
    dw LevelE9JSLs
    dw LevelEAJSLs
    dw LevelEBJSLs
    dw LevelECJSLs
    dw LevelEDJSLs
    dw LevelEEJSLs
    dw LevelEFJSLs
    dw LevelF0JSLs
    dw LevelF1JSLs
    dw LevelF2JSLs
    dw LevelF3JSLs
    dw LevelF4JSLs
    dw LevelF5JSLs
    dw LevelF6JSLs
    dw LevelF7JSLs
    dw LevelF8JSLs
    dw LevelF9JSLs
    dw LevelFAJSLs
    dw LevelFBJSLs
    dw LevelFCJSLs
    dw LevelFDJSLs
    dw LevelFEJSLs
    dw LevelFFJSLs
    dw Level100JSLs
    dw Level101JSLs
    dw Level102JSLs
    dw Level103JSLs
    dw Level104JSLs
    dw Level105JSLs
    dw Level106JSLs
    dw Level107JSLs
    dw Level108JSLs
    dw Level109JSLs
    dw Level10AJSLs
    dw Level10BJSLs
    dw Level10CJSLs
    dw Level10DJSLs
    dw Level10EJSLs
    dw Level10FJSLs
    dw Level110JSLs
    dw Level111JSLs
    dw Level112JSLs
    dw Level113JSLs
    dw Level114JSLs
    dw Level115JSLs
    dw Level116JSLs
    dw Level117JSLs
    dw Level118JSLs
    dw Level119JSLs
    dw Level11AJSLs
    dw Level11BJSLs
    dw Level11CJSLs
    dw Level11DJSLs
    dw Level11EJSLs
    dw Level11FJSLs
    dw Level120JSLs
    dw Level121JSLs
    dw Level122JSLs
    dw Level123JSLs
    dw Level124JSLs
    dw Level125JSLs
    dw Level126JSLs
    dw Level127JSLs
    dw Level128JSLs
    dw Level129JSLs
    dw Level12AJSLs
    dw Level12BJSLs
    dw Level12CJSLs
    dw Level12DJSLs
    dw Level12EJSLs
    dw Level12FJSLs
    dw Level130JSLs
    dw Level131JSLs
    dw Level132JSLs
    dw Level133JSLs
    dw Level134JSLs
    dw Level135JSLs
    dw Level136JSLs
    dw Level137JSLs
    dw Level138JSLs
    dw Level139JSLs
    dw Level13AJSLs
    dw Level13BJSLs
    dw Level13CJSLs
    dw Level13DJSLs
    dw Level13EJSLs
    dw Level13FJSLs
    dw Level140JSLs
    dw Level141JSLs
    dw Level142JSLs
    dw Level143JSLs
    dw Level144JSLs
    dw Level145JSLs
    dw Level146JSLs
    dw Level147JSLs
    dw Level148JSLs
    dw Level149JSLs
    dw Level14AJSLs
    dw Level14BJSLs
    dw Level14CJSLs
    dw Level14DJSLs
    dw Level14EJSLs
    dw Level14FJSLs
    dw Level150JSLs
    dw Level151JSLs
    dw Level152JSLs
    dw Level153JSLs
    dw Level154JSLs
    dw Level155JSLs
    dw Level156JSLs
    dw Level157JSLs
    dw Level158JSLs
    dw Level159JSLs
    dw Level15AJSLs
    dw Level15BJSLs
    dw Level15CJSLs
    dw Level15DJSLs
    dw Level15EJSLs
    dw Level15FJSLs
    dw Level160JSLs
    dw Level161JSLs
    dw Level162JSLs
    dw Level163JSLs
    dw Level164JSLs
    dw Level165JSLs
    dw Level166JSLs
    dw Level167JSLs
    dw Level168JSLs
    dw Level169JSLs
    dw Level16AJSLs
    dw Level16BJSLs
    dw Level16CJSLs
    dw Level16DJSLs
    dw Level16EJSLs
    dw Level16FJSLs
    dw Level170JSLs
    dw Level171JSLs
    dw Level172JSLs
    dw Level173JSLs
    dw Level174JSLs
    dw Level175JSLs
    dw Level176JSLs
    dw Level177JSLs
    dw Level178JSLs
    dw Level179JSLs
    dw Level17AJSLs
    dw Level17BJSLs
    dw Level17CJSLs
    dw Level17DJSLs
    dw Level17EJSLs
    dw Level17FJSLs
    dw Level180JSLs
    dw Level181JSLs
    dw Level182JSLs
    dw Level183JSLs
    dw Level184JSLs
    dw Level185JSLs
    dw Level186JSLs
    dw Level187JSLs
    dw Level188JSLs
    dw Level189JSLs
    dw Level18AJSLs
    dw Level18BJSLs
    dw Level18CJSLs
    dw Level18DJSLs
    dw Level18EJSLs
    dw Level18FJSLs
    dw Level190JSLs
    dw Level191JSLs
    dw Level192JSLs
    dw Level193JSLs
    dw Level194JSLs
    dw Level195JSLs
    dw Level196JSLs
    dw Level197JSLs
    dw Level198JSLs
    dw Level199JSLs
    dw Level19AJSLs
    dw Level19BJSLs
    dw Level19CJSLs
    dw Level19DJSLs
    dw Level19EJSLs
    dw Level19FJSLs
    dw Level1A0JSLs
    dw Level1A1JSLs
    dw Level1A2JSLs
    dw Level1A3JSLs
    dw Level1A4JSLs
    dw Level1A5JSLs
    dw Level1A6JSLs
    dw Level1A7JSLs
    dw Level1A8JSLs
    dw Level1A9JSLs
    dw Level1AAJSLs
    dw Level1ABJSLs
    dw Level1ACJSLs
    dw Level1ADJSLs
    dw Level1AEJSLs
    dw Level1AFJSLs
    dw Level1B0JSLs
    dw Level1B1JSLs
    dw Level1B2JSLs
    dw Level1B3JSLs
    dw Level1B4JSLs
    dw Level1B5JSLs
    dw Level1B6JSLs
    dw Level1B7JSLs
    dw Level1B8JSLs
    dw Level1B9JSLs
    dw Level1BAJSLs
    dw Level1BBJSLs
    dw Level1BCJSLs
    dw Level1BDJSLs
    dw Level1BEJSLs
    dw Level1BFJSLs
    dw Level1C0JSLs
    dw Level1C1JSLs
    dw Level1C2JSLs
    dw Level1C3JSLs
    dw Level1C4JSLs
    dw Level1C5JSLs
    dw Level1C6JSLs
    dw Level1C7JSLs
    dw Level1C8JSLs
    dw Level1C9JSLs
    dw Level1CAJSLs
    dw Level1CBJSLs
    dw Level1CCJSLs
    dw Level1CDJSLs
    dw Level1CEJSLs
    dw Level1CFJSLs
    dw Level1D0JSLs
    dw Level1D1JSLs
    dw Level1D2JSLs
    dw Level1D3JSLs
    dw Level1D4JSLs
    dw Level1D5JSLs
    dw Level1D6JSLs
    dw Level1D7JSLs
    dw Level1D8JSLs
    dw Level1D9JSLs
    dw Level1DAJSLs
    dw Level1DBJSLs
    dw Level1DCJSLs
    dw Level1DDJSLs
    dw Level1DEJSLs
    dw Level1DFJSLs
    dw Level1E0JSLs
    dw Level1E1JSLs
    dw Level1E2JSLs
    dw Level1E3JSLs
    dw Level1E4JSLs
    dw Level1E5JSLs
    dw Level1E6JSLs
    dw Level1E7JSLs
    dw Level1E8JSLs
    dw Level1E9JSLs
    dw Level1EAJSLs
    dw Level1EBJSLs
    dw Level1ECJSLs
    dw Level1EDJSLs
    dw Level1EEJSLs
    dw Level1EFJSLs
    dw Level1F0JSLs
    dw Level1F1JSLs
    dw Level1F2JSLs
    dw Level1F3JSLs
    dw Level1F4JSLs
    dw Level1F5JSLs
    dw Level1F6JSLs
    dw Level1F7JSLs
    dw Level1F8JSLs
    dw Level1F9JSLs
    dw Level1FAJSLs
    dw Level1FBJSLs
    dw Level1FCJSLs
    dw Level1FDJSLs
    dw Level1FEJSLs
    dw Level1FFJSLs

if !UberLevelNMINormal
    NMILevelResourcePointers:
        dw Level0NMIJSLs
        dw Level1NMIJSLs
        dw Level2NMIJSLs
        dw Level3NMIJSLs
        dw Level4NMIJSLs
        dw Level5NMIJSLs
        dw Level6NMIJSLs
        dw Level7NMIJSLs
        dw Level8NMIJSLs
        dw Level9NMIJSLs
        dw LevelANMIJSLs
        dw LevelBNMIJSLs
        dw LevelCNMIJSLs
        dw LevelDNMIJSLs
        dw LevelENMIJSLs
        dw LevelFNMIJSLs
        dw Level10NMIJSLs
        dw Level11NMIJSLs
        dw Level12NMIJSLs
        dw Level13NMIJSLs
        dw Level14NMIJSLs
        dw Level15NMIJSLs
        dw Level16NMIJSLs
        dw Level17NMIJSLs
        dw Level18NMIJSLs
        dw Level19NMIJSLs
        dw Level1ANMIJSLs
        dw Level1BNMIJSLs
        dw Level1CNMIJSLs
        dw Level1DNMIJSLs
        dw Level1ENMIJSLs
        dw Level1FNMIJSLs
        dw Level20NMIJSLs
        dw Level21NMIJSLs
        dw Level22NMIJSLs
        dw Level23NMIJSLs
        dw Level24NMIJSLs
        dw Level25NMIJSLs
        dw Level26NMIJSLs
        dw Level27NMIJSLs
        dw Level28NMIJSLs
        dw Level29NMIJSLs
        dw Level2ANMIJSLs
        dw Level2BNMIJSLs
        dw Level2CNMIJSLs
        dw Level2DNMIJSLs
        dw Level2ENMIJSLs
        dw Level2FNMIJSLs
        dw Level30NMIJSLs
        dw Level31NMIJSLs
        dw Level32NMIJSLs
        dw Level33NMIJSLs
        dw Level34NMIJSLs
        dw Level35NMIJSLs
        dw Level36NMIJSLs
        dw Level37NMIJSLs
        dw Level38NMIJSLs
        dw Level39NMIJSLs
        dw Level3ANMIJSLs
        dw Level3BNMIJSLs
        dw Level3CNMIJSLs
        dw Level3DNMIJSLs
        dw Level3ENMIJSLs
        dw Level3FNMIJSLs
        dw Level40NMIJSLs
        dw Level41NMIJSLs
        dw Level42NMIJSLs
        dw Level43NMIJSLs
        dw Level44NMIJSLs
        dw Level45NMIJSLs
        dw Level46NMIJSLs
        dw Level47NMIJSLs
        dw Level48NMIJSLs
        dw Level49NMIJSLs
        dw Level4ANMIJSLs
        dw Level4BNMIJSLs
        dw Level4CNMIJSLs
        dw Level4DNMIJSLs
        dw Level4ENMIJSLs
        dw Level4FNMIJSLs
        dw Level50NMIJSLs
        dw Level51NMIJSLs
        dw Level52NMIJSLs
        dw Level53NMIJSLs
        dw Level54NMIJSLs
        dw Level55NMIJSLs
        dw Level56NMIJSLs
        dw Level57NMIJSLs
        dw Level58NMIJSLs
        dw Level59NMIJSLs
        dw Level5ANMIJSLs
        dw Level5BNMIJSLs
        dw Level5CNMIJSLs
        dw Level5DNMIJSLs
        dw Level5ENMIJSLs
        dw Level5FNMIJSLs
        dw Level60NMIJSLs
        dw Level61NMIJSLs
        dw Level62NMIJSLs
        dw Level63NMIJSLs
        dw Level64NMIJSLs
        dw Level65NMIJSLs
        dw Level66NMIJSLs
        dw Level67NMIJSLs
        dw Level68NMIJSLs
        dw Level69NMIJSLs
        dw Level6ANMIJSLs
        dw Level6BNMIJSLs
        dw Level6CNMIJSLs
        dw Level6DNMIJSLs
        dw Level6ENMIJSLs
        dw Level6FNMIJSLs
        dw Level70NMIJSLs
        dw Level71NMIJSLs
        dw Level72NMIJSLs
        dw Level73NMIJSLs
        dw Level74NMIJSLs
        dw Level75NMIJSLs
        dw Level76NMIJSLs
        dw Level77NMIJSLs
        dw Level78NMIJSLs
        dw Level79NMIJSLs
        dw Level7ANMIJSLs
        dw Level7BNMIJSLs
        dw Level7CNMIJSLs
        dw Level7DNMIJSLs
        dw Level7ENMIJSLs
        dw Level7FNMIJSLs
        dw Level80NMIJSLs
        dw Level81NMIJSLs
        dw Level82NMIJSLs
        dw Level83NMIJSLs
        dw Level84NMIJSLs
        dw Level85NMIJSLs
        dw Level86NMIJSLs
        dw Level87NMIJSLs
        dw Level88NMIJSLs
        dw Level89NMIJSLs
        dw Level8ANMIJSLs
        dw Level8BNMIJSLs
        dw Level8CNMIJSLs
        dw Level8DNMIJSLs
        dw Level8ENMIJSLs
        dw Level8FNMIJSLs
        dw Level90NMIJSLs
        dw Level91NMIJSLs
        dw Level92NMIJSLs
        dw Level93NMIJSLs
        dw Level94NMIJSLs
        dw Level95NMIJSLs
        dw Level96NMIJSLs
        dw Level97NMIJSLs
        dw Level98NMIJSLs
        dw Level99NMIJSLs
        dw Level9ANMIJSLs
        dw Level9BNMIJSLs
        dw Level9CNMIJSLs
        dw Level9DNMIJSLs
        dw Level9ENMIJSLs
        dw Level9FNMIJSLs
        dw LevelA0NMIJSLs
        dw LevelA1NMIJSLs
        dw LevelA2NMIJSLs
        dw LevelA3NMIJSLs
        dw LevelA4NMIJSLs
        dw LevelA5NMIJSLs
        dw LevelA6NMIJSLs
        dw LevelA7NMIJSLs
        dw LevelA8NMIJSLs
        dw LevelA9NMIJSLs
        dw LevelAANMIJSLs
        dw LevelABNMIJSLs
        dw LevelACNMIJSLs
        dw LevelADNMIJSLs
        dw LevelAENMIJSLs
        dw LevelAFNMIJSLs
        dw LevelB0NMIJSLs
        dw LevelB1NMIJSLs
        dw LevelB2NMIJSLs
        dw LevelB3NMIJSLs
        dw LevelB4NMIJSLs
        dw LevelB5NMIJSLs
        dw LevelB6NMIJSLs
        dw LevelB7NMIJSLs
        dw LevelB8NMIJSLs
        dw LevelB9NMIJSLs
        dw LevelBANMIJSLs
        dw LevelBBNMIJSLs
        dw LevelBCNMIJSLs
        dw LevelBDNMIJSLs
        dw LevelBENMIJSLs
        dw LevelBFNMIJSLs
        dw LevelC0NMIJSLs
        dw LevelC1NMIJSLs
        dw LevelC2NMIJSLs
        dw LevelC3NMIJSLs
        dw LevelC4NMIJSLs
        dw LevelC5NMIJSLs
        dw LevelC6NMIJSLs
        dw LevelC7NMIJSLs
        dw LevelC8NMIJSLs
        dw LevelC9NMIJSLs
        dw LevelCANMIJSLs
        dw LevelCBNMIJSLs
        dw LevelCCNMIJSLs
        dw LevelCDNMIJSLs
        dw LevelCENMIJSLs
        dw LevelCFNMIJSLs
        dw LevelD0NMIJSLs
        dw LevelD1NMIJSLs
        dw LevelD2NMIJSLs
        dw LevelD3NMIJSLs
        dw LevelD4NMIJSLs
        dw LevelD5NMIJSLs
        dw LevelD6NMIJSLs
        dw LevelD7NMIJSLs
        dw LevelD8NMIJSLs
        dw LevelD9NMIJSLs
        dw LevelDANMIJSLs
        dw LevelDBNMIJSLs
        dw LevelDCNMIJSLs
        dw LevelDDNMIJSLs
        dw LevelDENMIJSLs
        dw LevelDFNMIJSLs
        dw LevelE0NMIJSLs
        dw LevelE1NMIJSLs
        dw LevelE2NMIJSLs
        dw LevelE3NMIJSLs
        dw LevelE4NMIJSLs
        dw LevelE5NMIJSLs
        dw LevelE6NMIJSLs
        dw LevelE7NMIJSLs
        dw LevelE8NMIJSLs
        dw LevelE9NMIJSLs
        dw LevelEANMIJSLs
        dw LevelEBNMIJSLs
        dw LevelECNMIJSLs
        dw LevelEDNMIJSLs
        dw LevelEENMIJSLs
        dw LevelEFNMIJSLs
        dw LevelF0NMIJSLs
        dw LevelF1NMIJSLs
        dw LevelF2NMIJSLs
        dw LevelF3NMIJSLs
        dw LevelF4NMIJSLs
        dw LevelF5NMIJSLs
        dw LevelF6NMIJSLs
        dw LevelF7NMIJSLs
        dw LevelF8NMIJSLs
        dw LevelF9NMIJSLs
        dw LevelFANMIJSLs
        dw LevelFBNMIJSLs
        dw LevelFCNMIJSLs
        dw LevelFDNMIJSLs
        dw LevelFENMIJSLs
        dw LevelFFNMIJSLs
        dw Level100NMIJSLs
        dw Level101NMIJSLs
        dw Level102NMIJSLs
        dw Level103NMIJSLs
        dw Level104NMIJSLs
        dw Level105NMIJSLs
        dw Level106NMIJSLs
        dw Level107NMIJSLs
        dw Level108NMIJSLs
        dw Level109NMIJSLs
        dw Level10ANMIJSLs
        dw Level10BNMIJSLs
        dw Level10CNMIJSLs
        dw Level10DNMIJSLs
        dw Level10ENMIJSLs
        dw Level10FNMIJSLs
        dw Level110NMIJSLs
        dw Level111NMIJSLs
        dw Level112NMIJSLs
        dw Level113NMIJSLs
        dw Level114NMIJSLs
        dw Level115NMIJSLs
        dw Level116NMIJSLs
        dw Level117NMIJSLs
        dw Level118NMIJSLs
        dw Level119NMIJSLs
        dw Level11ANMIJSLs
        dw Level11BNMIJSLs
        dw Level11CNMIJSLs
        dw Level11DNMIJSLs
        dw Level11ENMIJSLs
        dw Level11FNMIJSLs
        dw Level120NMIJSLs
        dw Level121NMIJSLs
        dw Level122NMIJSLs
        dw Level123NMIJSLs
        dw Level124NMIJSLs
        dw Level125NMIJSLs
        dw Level126NMIJSLs
        dw Level127NMIJSLs
        dw Level128NMIJSLs
        dw Level129NMIJSLs
        dw Level12ANMIJSLs
        dw Level12BNMIJSLs
        dw Level12CNMIJSLs
        dw Level12DNMIJSLs
        dw Level12ENMIJSLs
        dw Level12FNMIJSLs
        dw Level130NMIJSLs
        dw Level131NMIJSLs
        dw Level132NMIJSLs
        dw Level133NMIJSLs
        dw Level134NMIJSLs
        dw Level135NMIJSLs
        dw Level136NMIJSLs
        dw Level137NMIJSLs
        dw Level138NMIJSLs
        dw Level139NMIJSLs
        dw Level13ANMIJSLs
        dw Level13BNMIJSLs
        dw Level13CNMIJSLs
        dw Level13DNMIJSLs
        dw Level13ENMIJSLs
        dw Level13FNMIJSLs
        dw Level140NMIJSLs
        dw Level141NMIJSLs
        dw Level142NMIJSLs
        dw Level143NMIJSLs
        dw Level144NMIJSLs
        dw Level145NMIJSLs
        dw Level146NMIJSLs
        dw Level147NMIJSLs
        dw Level148NMIJSLs
        dw Level149NMIJSLs
        dw Level14ANMIJSLs
        dw Level14BNMIJSLs
        dw Level14CNMIJSLs
        dw Level14DNMIJSLs
        dw Level14ENMIJSLs
        dw Level14FNMIJSLs
        dw Level150NMIJSLs
        dw Level151NMIJSLs
        dw Level152NMIJSLs
        dw Level153NMIJSLs
        dw Level154NMIJSLs
        dw Level155NMIJSLs
        dw Level156NMIJSLs
        dw Level157NMIJSLs
        dw Level158NMIJSLs
        dw Level159NMIJSLs
        dw Level15ANMIJSLs
        dw Level15BNMIJSLs
        dw Level15CNMIJSLs
        dw Level15DNMIJSLs
        dw Level15ENMIJSLs
        dw Level15FNMIJSLs
        dw Level160NMIJSLs
        dw Level161NMIJSLs
        dw Level162NMIJSLs
        dw Level163NMIJSLs
        dw Level164NMIJSLs
        dw Level165NMIJSLs
        dw Level166NMIJSLs
        dw Level167NMIJSLs
        dw Level168NMIJSLs
        dw Level169NMIJSLs
        dw Level16ANMIJSLs
        dw Level16BNMIJSLs
        dw Level16CNMIJSLs
        dw Level16DNMIJSLs
        dw Level16ENMIJSLs
        dw Level16FNMIJSLs
        dw Level170NMIJSLs
        dw Level171NMIJSLs
        dw Level172NMIJSLs
        dw Level173NMIJSLs
        dw Level174NMIJSLs
        dw Level175NMIJSLs
        dw Level176NMIJSLs
        dw Level177NMIJSLs
        dw Level178NMIJSLs
        dw Level179NMIJSLs
        dw Level17ANMIJSLs
        dw Level17BNMIJSLs
        dw Level17CNMIJSLs
        dw Level17DNMIJSLs
        dw Level17ENMIJSLs
        dw Level17FNMIJSLs
        dw Level180NMIJSLs
        dw Level181NMIJSLs
        dw Level182NMIJSLs
        dw Level183NMIJSLs
        dw Level184NMIJSLs
        dw Level185NMIJSLs
        dw Level186NMIJSLs
        dw Level187NMIJSLs
        dw Level188NMIJSLs
        dw Level189NMIJSLs
        dw Level18ANMIJSLs
        dw Level18BNMIJSLs
        dw Level18CNMIJSLs
        dw Level18DNMIJSLs
        dw Level18ENMIJSLs
        dw Level18FNMIJSLs
        dw Level190NMIJSLs
        dw Level191NMIJSLs
        dw Level192NMIJSLs
        dw Level193NMIJSLs
        dw Level194NMIJSLs
        dw Level195NMIJSLs
        dw Level196NMIJSLs
        dw Level197NMIJSLs
        dw Level198NMIJSLs
        dw Level199NMIJSLs
        dw Level19ANMIJSLs
        dw Level19BNMIJSLs
        dw Level19CNMIJSLs
        dw Level19DNMIJSLs
        dw Level19ENMIJSLs
        dw Level19FNMIJSLs
        dw Level1A0NMIJSLs
        dw Level1A1NMIJSLs
        dw Level1A2NMIJSLs
        dw Level1A3NMIJSLs
        dw Level1A4NMIJSLs
        dw Level1A5NMIJSLs
        dw Level1A6NMIJSLs
        dw Level1A7NMIJSLs
        dw Level1A8NMIJSLs
        dw Level1A9NMIJSLs
        dw Level1AANMIJSLs
        dw Level1ABNMIJSLs
        dw Level1ACNMIJSLs
        dw Level1ADNMIJSLs
        dw Level1AENMIJSLs
        dw Level1AFNMIJSLs
        dw Level1B0NMIJSLs
        dw Level1B1NMIJSLs
        dw Level1B2NMIJSLs
        dw Level1B3NMIJSLs
        dw Level1B4NMIJSLs
        dw Level1B5NMIJSLs
        dw Level1B6NMIJSLs
        dw Level1B7NMIJSLs
        dw Level1B8NMIJSLs
        dw Level1B9NMIJSLs
        dw Level1BANMIJSLs
        dw Level1BBNMIJSLs
        dw Level1BCNMIJSLs
        dw Level1BDNMIJSLs
        dw Level1BENMIJSLs
        dw Level1BFNMIJSLs
        dw Level1C0NMIJSLs
        dw Level1C1NMIJSLs
        dw Level1C2NMIJSLs
        dw Level1C3NMIJSLs
        dw Level1C4NMIJSLs
        dw Level1C5NMIJSLs
        dw Level1C6NMIJSLs
        dw Level1C7NMIJSLs
        dw Level1C8NMIJSLs
        dw Level1C9NMIJSLs
        dw Level1CANMIJSLs
        dw Level1CBNMIJSLs
        dw Level1CCNMIJSLs
        dw Level1CDNMIJSLs
        dw Level1CENMIJSLs
        dw Level1CFNMIJSLs
        dw Level1D0NMIJSLs
        dw Level1D1NMIJSLs
        dw Level1D2NMIJSLs
        dw Level1D3NMIJSLs
        dw Level1D4NMIJSLs
        dw Level1D5NMIJSLs
        dw Level1D6NMIJSLs
        dw Level1D7NMIJSLs
        dw Level1D8NMIJSLs
        dw Level1D9NMIJSLs
        dw Level1DANMIJSLs
        dw Level1DBNMIJSLs
        dw Level1DCNMIJSLs
        dw Level1DDNMIJSLs
        dw Level1DENMIJSLs
        dw Level1DFNMIJSLs
        dw Level1E0NMIJSLs
        dw Level1E1NMIJSLs
        dw Level1E2NMIJSLs
        dw Level1E3NMIJSLs
        dw Level1E4NMIJSLs
        dw Level1E5NMIJSLs
        dw Level1E6NMIJSLs
        dw Level1E7NMIJSLs
        dw Level1E8NMIJSLs
        dw Level1E9NMIJSLs
        dw Level1EANMIJSLs
        dw Level1EBNMIJSLs
        dw Level1ECNMIJSLs
        dw Level1EDNMIJSLs
        dw Level1EENMIJSLs
        dw Level1EFNMIJSLs
        dw Level1F0NMIJSLs
        dw Level1F1NMIJSLs
        dw Level1F2NMIJSLs
        dw Level1F3NMIJSLs
        dw Level1F4NMIJSLs
        dw Level1F5NMIJSLs
        dw Level1F6NMIJSLs
        dw Level1F7NMIJSLs
        dw Level1F8NMIJSLs
        dw Level1F9NMIJSLs
        dw Level1FANMIJSLs
        dw Level1FBNMIJSLs
        dw Level1FCNMIJSLs
        dw Level1FDNMIJSLs
        dw Level1FENMIJSLs
        dw Level1FFNMIJSLs
endif

GamemodeResourcePointers:
    dw Gamemode0JSLs
    dw Gamemode1JSLs
    dw Gamemode2JSLs
    dw Gamemode3JSLs
    dw Gamemode4JSLs
    dw Gamemode5JSLs
    dw Gamemode6JSLs
    dw Gamemode7JSLs
    dw Gamemode8JSLs
    dw Gamemode9JSLs
    dw GamemodeAJSLs
    dw GamemodeBJSLs
    dw GamemodeCJSLs
    dw GamemodeDJSLs
    dw GamemodeEJSLs
    dw GamemodeFJSLs
    dw Gamemode10JSLs
    dw Gamemode11JSLs
    dw Gamemode12JSLs
    dw Gamemode13JSLs
    dw Gamemode14JSLs
    dw Gamemode15JSLs
    dw Gamemode16JSLs
    dw Gamemode17JSLs
    dw Gamemode18JSLs
    dw Gamemode19JSLs
    dw Gamemode1AJSLs
    dw Gamemode1BJSLs
    dw Gamemode1CJSLs
    dw Gamemode1DJSLs
    dw Gamemode1EJSLs
    dw Gamemode1FJSLs
    dw Gamemode20JSLs
    dw Gamemode21JSLs
    dw Gamemode22JSLs
    dw Gamemode23JSLs
    dw Gamemode24JSLs
    dw Gamemode25JSLs
    dw Gamemode26JSLs
    dw Gamemode27JSLs
    dw Gamemode28JSLs
    dw Gamemode29JSLs
    dw Gamemode2AJSLs
    dw Gamemode2BJSLs
    dw Gamemode2CJSLs
    dw Gamemode2DJSLs
    dw Gamemode2EJSLs
    dw Gamemode2FJSLs
    dw Gamemode30JSLs
    dw Gamemode31JSLs
    dw Gamemode32JSLs
    dw Gamemode33JSLs
    dw Gamemode34JSLs
    dw Gamemode35JSLs
    dw Gamemode36JSLs
    dw Gamemode37JSLs
    dw Gamemode38JSLs
    dw Gamemode39JSLs
    dw Gamemode3AJSLs
    dw Gamemode3BJSLs
    dw Gamemode3CJSLs
    dw Gamemode3DJSLs
    dw Gamemode3EJSLs
    dw Gamemode3FJSLs
    dw Gamemode40JSLs
    dw Gamemode41JSLs
    dw Gamemode42JSLs
    dw Gamemode43JSLs
    dw Gamemode44JSLs
    dw Gamemode45JSLs
    dw Gamemode46JSLs
    dw Gamemode47JSLs
    dw Gamemode48JSLs
    dw Gamemode49JSLs
    dw Gamemode4AJSLs
    dw Gamemode4BJSLs
    dw Gamemode4CJSLs
    dw Gamemode4DJSLs
    dw Gamemode4EJSLs
    dw Gamemode4FJSLs
    dw Gamemode50JSLs
    dw Gamemode51JSLs
    dw Gamemode52JSLs
    dw Gamemode53JSLs
    dw Gamemode54JSLs
    dw Gamemode55JSLs
    dw Gamemode56JSLs
    dw Gamemode57JSLs
    dw Gamemode58JSLs
    dw Gamemode59JSLs
    dw Gamemode5AJSLs
    dw Gamemode5BJSLs
    dw Gamemode5CJSLs
    dw Gamemode5DJSLs
    dw Gamemode5EJSLs
    dw Gamemode5FJSLs
    dw Gamemode60JSLs
    dw Gamemode61JSLs
    dw Gamemode62JSLs
    dw Gamemode63JSLs
    dw Gamemode64JSLs
    dw Gamemode65JSLs
    dw Gamemode66JSLs
    dw Gamemode67JSLs
    dw Gamemode68JSLs
    dw Gamemode69JSLs
    dw Gamemode6AJSLs
    dw Gamemode6BJSLs
    dw Gamemode6CJSLs
    dw Gamemode6DJSLs
    dw Gamemode6EJSLs
    dw Gamemode6FJSLs
    dw Gamemode70JSLs
    dw Gamemode71JSLs
    dw Gamemode72JSLs
    dw Gamemode73JSLs
    dw Gamemode74JSLs
    dw Gamemode75JSLs
    dw Gamemode76JSLs
    dw Gamemode77JSLs
    dw Gamemode78JSLs
    dw Gamemode79JSLs
    dw Gamemode7AJSLs
    dw Gamemode7BJSLs
    dw Gamemode7CJSLs
    dw Gamemode7DJSLs
    dw Gamemode7EJSLs
    dw Gamemode7FJSLs
    dw Gamemode80JSLs
    dw Gamemode81JSLs
    dw Gamemode82JSLs
    dw Gamemode83JSLs
    dw Gamemode84JSLs
    dw Gamemode85JSLs
    dw Gamemode86JSLs
    dw Gamemode87JSLs
    dw Gamemode88JSLs
    dw Gamemode89JSLs
    dw Gamemode8AJSLs
    dw Gamemode8BJSLs
    dw Gamemode8CJSLs
    dw Gamemode8DJSLs
    dw Gamemode8EJSLs
    dw Gamemode8FJSLs
    dw Gamemode90JSLs
    dw Gamemode91JSLs
    dw Gamemode92JSLs
    dw Gamemode93JSLs
    dw Gamemode94JSLs
    dw Gamemode95JSLs
    dw Gamemode96JSLs
    dw Gamemode97JSLs
    dw Gamemode98JSLs
    dw Gamemode99JSLs
    dw Gamemode9AJSLs
    dw Gamemode9BJSLs
    dw Gamemode9CJSLs
    dw Gamemode9DJSLs
    dw Gamemode9EJSLs
    dw Gamemode9FJSLs
    dw GamemodeA0JSLs
    dw GamemodeA1JSLs
    dw GamemodeA2JSLs
    dw GamemodeA3JSLs
    dw GamemodeA4JSLs
    dw GamemodeA5JSLs
    dw GamemodeA6JSLs
    dw GamemodeA7JSLs
    dw GamemodeA8JSLs
    dw GamemodeA9JSLs
    dw GamemodeAAJSLs
    dw GamemodeABJSLs
    dw GamemodeACJSLs
    dw GamemodeADJSLs
    dw GamemodeAEJSLs
    dw GamemodeAFJSLs
    dw GamemodeB0JSLs
    dw GamemodeB1JSLs
    dw GamemodeB2JSLs
    dw GamemodeB3JSLs
    dw GamemodeB4JSLs
    dw GamemodeB5JSLs
    dw GamemodeB6JSLs
    dw GamemodeB7JSLs
    dw GamemodeB8JSLs
    dw GamemodeB9JSLs
    dw GamemodeBAJSLs
    dw GamemodeBBJSLs
    dw GamemodeBCJSLs
    dw GamemodeBDJSLs
    dw GamemodeBEJSLs
    dw GamemodeBFJSLs
    dw GamemodeC0JSLs
    dw GamemodeC1JSLs
    dw GamemodeC2JSLs
    dw GamemodeC3JSLs
    dw GamemodeC4JSLs
    dw GamemodeC5JSLs
    dw GamemodeC6JSLs
    dw GamemodeC7JSLs
    dw GamemodeC8JSLs
    dw GamemodeC9JSLs
    dw GamemodeCAJSLs
    dw GamemodeCBJSLs
    dw GamemodeCCJSLs
    dw GamemodeCDJSLs
    dw GamemodeCEJSLs
    dw GamemodeCFJSLs
    dw GamemodeD0JSLs
    dw GamemodeD1JSLs
    dw GamemodeD2JSLs
    dw GamemodeD3JSLs
    dw GamemodeD4JSLs
    dw GamemodeD5JSLs
    dw GamemodeD6JSLs
    dw GamemodeD7JSLs
    dw GamemodeD8JSLs
    dw GamemodeD9JSLs
    dw GamemodeDAJSLs
    dw GamemodeDBJSLs
    dw GamemodeDCJSLs
    dw GamemodeDDJSLs
    dw GamemodeDEJSLs
    dw GamemodeDFJSLs
    dw GamemodeE0JSLs
    dw GamemodeE1JSLs
    dw GamemodeE2JSLs
    dw GamemodeE3JSLs
    dw GamemodeE4JSLs
    dw GamemodeE5JSLs
    dw GamemodeE6JSLs
    dw GamemodeE7JSLs
    dw GamemodeE8JSLs
    dw GamemodeE9JSLs
    dw GamemodeEAJSLs
    dw GamemodeEBJSLs
    dw GamemodeECJSLs
    dw GamemodeEDJSLs
    dw GamemodeEEJSLs
    dw GamemodeEFJSLs
    dw GamemodeF0JSLs
    dw GamemodeF1JSLs
    dw GamemodeF2JSLs
    dw GamemodeF3JSLs
    dw GamemodeF4JSLs
    dw GamemodeF5JSLs
    dw GamemodeF6JSLs
    dw GamemodeF7JSLs
    dw GamemodeF8JSLs
    dw GamemodeF9JSLs
    dw GamemodeFAJSLs
    dw GamemodeFBJSLs
    dw GamemodeFCJSLs
    dw GamemodeFDJSLs
    dw GamemodeFEJSLs
    dw GamemodeFFJSLs


if !UberGamemodeNMINormal
    NMIGamemodeResourcePointers:
        dw Gamemode0NMIJSLs
        dw Gamemode1NMIJSLs
        dw Gamemode2NMIJSLs
        dw Gamemode3NMIJSLs
        dw Gamemode4NMIJSLs
        dw Gamemode5NMIJSLs
        dw Gamemode6NMIJSLs
        dw Gamemode7NMIJSLs
        dw Gamemode8NMIJSLs
        dw Gamemode9NMIJSLs
        dw GamemodeANMIJSLs
        dw GamemodeBNMIJSLs
        dw GamemodeCNMIJSLs
        dw GamemodeDNMIJSLs
        dw GamemodeENMIJSLs
        dw GamemodeFNMIJSLs
        dw Gamemode10NMIJSLs
        dw Gamemode11NMIJSLs
        dw Gamemode12NMIJSLs
        dw Gamemode13NMIJSLs
        dw Gamemode14NMIJSLs
        dw Gamemode15NMIJSLs
        dw Gamemode16NMIJSLs
        dw Gamemode17NMIJSLs
        dw Gamemode18NMIJSLs
        dw Gamemode19NMIJSLs
        dw Gamemode1ANMIJSLs
        dw Gamemode1BNMIJSLs
        dw Gamemode1CNMIJSLs
        dw Gamemode1DNMIJSLs
        dw Gamemode1ENMIJSLs
        dw Gamemode1FNMIJSLs
        dw Gamemode20NMIJSLs
        dw Gamemode21NMIJSLs
        dw Gamemode22NMIJSLs
        dw Gamemode23NMIJSLs
        dw Gamemode24NMIJSLs
        dw Gamemode25NMIJSLs
        dw Gamemode26NMIJSLs
        dw Gamemode27NMIJSLs
        dw Gamemode28NMIJSLs
        dw Gamemode29NMIJSLs
        dw Gamemode2ANMIJSLs
        dw Gamemode2BNMIJSLs
        dw Gamemode2CNMIJSLs
        dw Gamemode2DNMIJSLs
        dw Gamemode2ENMIJSLs
        dw Gamemode2FNMIJSLs
        dw Gamemode30NMIJSLs
        dw Gamemode31NMIJSLs
        dw Gamemode32NMIJSLs
        dw Gamemode33NMIJSLs
        dw Gamemode34NMIJSLs
        dw Gamemode35NMIJSLs
        dw Gamemode36NMIJSLs
        dw Gamemode37NMIJSLs
        dw Gamemode38NMIJSLs
        dw Gamemode39NMIJSLs
        dw Gamemode3ANMIJSLs
        dw Gamemode3BNMIJSLs
        dw Gamemode3CNMIJSLs
        dw Gamemode3DNMIJSLs
        dw Gamemode3ENMIJSLs
        dw Gamemode3FNMIJSLs
        dw Gamemode40NMIJSLs
        dw Gamemode41NMIJSLs
        dw Gamemode42NMIJSLs
        dw Gamemode43NMIJSLs
        dw Gamemode44NMIJSLs
        dw Gamemode45NMIJSLs
        dw Gamemode46NMIJSLs
        dw Gamemode47NMIJSLs
        dw Gamemode48NMIJSLs
        dw Gamemode49NMIJSLs
        dw Gamemode4ANMIJSLs
        dw Gamemode4BNMIJSLs
        dw Gamemode4CNMIJSLs
        dw Gamemode4DNMIJSLs
        dw Gamemode4ENMIJSLs
        dw Gamemode4FNMIJSLs
        dw Gamemode50NMIJSLs
        dw Gamemode51NMIJSLs
        dw Gamemode52NMIJSLs
        dw Gamemode53NMIJSLs
        dw Gamemode54NMIJSLs
        dw Gamemode55NMIJSLs
        dw Gamemode56NMIJSLs
        dw Gamemode57NMIJSLs
        dw Gamemode58NMIJSLs
        dw Gamemode59NMIJSLs
        dw Gamemode5ANMIJSLs
        dw Gamemode5BNMIJSLs
        dw Gamemode5CNMIJSLs
        dw Gamemode5DNMIJSLs
        dw Gamemode5ENMIJSLs
        dw Gamemode5FNMIJSLs
        dw Gamemode60NMIJSLs
        dw Gamemode61NMIJSLs
        dw Gamemode62NMIJSLs
        dw Gamemode63NMIJSLs
        dw Gamemode64NMIJSLs
        dw Gamemode65NMIJSLs
        dw Gamemode66NMIJSLs
        dw Gamemode67NMIJSLs
        dw Gamemode68NMIJSLs
        dw Gamemode69NMIJSLs
        dw Gamemode6ANMIJSLs
        dw Gamemode6BNMIJSLs
        dw Gamemode6CNMIJSLs
        dw Gamemode6DNMIJSLs
        dw Gamemode6ENMIJSLs
        dw Gamemode6FNMIJSLs
        dw Gamemode70NMIJSLs
        dw Gamemode71NMIJSLs
        dw Gamemode72NMIJSLs
        dw Gamemode73NMIJSLs
        dw Gamemode74NMIJSLs
        dw Gamemode75NMIJSLs
        dw Gamemode76NMIJSLs
        dw Gamemode77NMIJSLs
        dw Gamemode78NMIJSLs
        dw Gamemode79NMIJSLs
        dw Gamemode7ANMIJSLs
        dw Gamemode7BNMIJSLs
        dw Gamemode7CNMIJSLs
        dw Gamemode7DNMIJSLs
        dw Gamemode7ENMIJSLs
        dw Gamemode7FNMIJSLs
        dw Gamemode80NMIJSLs
        dw Gamemode81NMIJSLs
        dw Gamemode82NMIJSLs
        dw Gamemode83NMIJSLs
        dw Gamemode84NMIJSLs
        dw Gamemode85NMIJSLs
        dw Gamemode86NMIJSLs
        dw Gamemode87NMIJSLs
        dw Gamemode88NMIJSLs
        dw Gamemode89NMIJSLs
        dw Gamemode8ANMIJSLs
        dw Gamemode8BNMIJSLs
        dw Gamemode8CNMIJSLs
        dw Gamemode8DNMIJSLs
        dw Gamemode8ENMIJSLs
        dw Gamemode8FNMIJSLs
        dw Gamemode90NMIJSLs
        dw Gamemode91NMIJSLs
        dw Gamemode92NMIJSLs
        dw Gamemode93NMIJSLs
        dw Gamemode94NMIJSLs
        dw Gamemode95NMIJSLs
        dw Gamemode96NMIJSLs
        dw Gamemode97NMIJSLs
        dw Gamemode98NMIJSLs
        dw Gamemode99NMIJSLs
        dw Gamemode9ANMIJSLs
        dw Gamemode9BNMIJSLs
        dw Gamemode9CNMIJSLs
        dw Gamemode9DNMIJSLs
        dw Gamemode9ENMIJSLs
        dw Gamemode9FNMIJSLs
        dw GamemodeA0NMIJSLs
        dw GamemodeA1NMIJSLs
        dw GamemodeA2NMIJSLs
        dw GamemodeA3NMIJSLs
        dw GamemodeA4NMIJSLs
        dw GamemodeA5NMIJSLs
        dw GamemodeA6NMIJSLs
        dw GamemodeA7NMIJSLs
        dw GamemodeA8NMIJSLs
        dw GamemodeA9NMIJSLs
        dw GamemodeAANMIJSLs
        dw GamemodeABNMIJSLs
        dw GamemodeACNMIJSLs
        dw GamemodeADNMIJSLs
        dw GamemodeAENMIJSLs
        dw GamemodeAFNMIJSLs
        dw GamemodeB0NMIJSLs
        dw GamemodeB1NMIJSLs
        dw GamemodeB2NMIJSLs
        dw GamemodeB3NMIJSLs
        dw GamemodeB4NMIJSLs
        dw GamemodeB5NMIJSLs
        dw GamemodeB6NMIJSLs
        dw GamemodeB7NMIJSLs
        dw GamemodeB8NMIJSLs
        dw GamemodeB9NMIJSLs
        dw GamemodeBANMIJSLs
        dw GamemodeBBNMIJSLs
        dw GamemodeBCNMIJSLs
        dw GamemodeBDNMIJSLs
        dw GamemodeBENMIJSLs
        dw GamemodeBFNMIJSLs
        dw GamemodeC0NMIJSLs
        dw GamemodeC1NMIJSLs
        dw GamemodeC2NMIJSLs
        dw GamemodeC3NMIJSLs
        dw GamemodeC4NMIJSLs
        dw GamemodeC5NMIJSLs
        dw GamemodeC6NMIJSLs
        dw GamemodeC7NMIJSLs
        dw GamemodeC8NMIJSLs
        dw GamemodeC9NMIJSLs
        dw GamemodeCANMIJSLs
        dw GamemodeCBNMIJSLs
        dw GamemodeCCNMIJSLs
        dw GamemodeCDNMIJSLs
        dw GamemodeCENMIJSLs
        dw GamemodeCFNMIJSLs
        dw GamemodeD0NMIJSLs
        dw GamemodeD1NMIJSLs
        dw GamemodeD2NMIJSLs
        dw GamemodeD3NMIJSLs
        dw GamemodeD4NMIJSLs
        dw GamemodeD5NMIJSLs
        dw GamemodeD6NMIJSLs
        dw GamemodeD7NMIJSLs
        dw GamemodeD8NMIJSLs
        dw GamemodeD9NMIJSLs
        dw GamemodeDANMIJSLs
        dw GamemodeDBNMIJSLs
        dw GamemodeDCNMIJSLs
        dw GamemodeDDNMIJSLs
        dw GamemodeDENMIJSLs
        dw GamemodeDFNMIJSLs
        dw GamemodeE0NMIJSLs
        dw GamemodeE1NMIJSLs
        dw GamemodeE2NMIJSLs
        dw GamemodeE3NMIJSLs
        dw GamemodeE4NMIJSLs
        dw GamemodeE5NMIJSLs
        dw GamemodeE6NMIJSLs
        dw GamemodeE7NMIJSLs
        dw GamemodeE8NMIJSLs
        dw GamemodeE9NMIJSLs
        dw GamemodeEANMIJSLs
        dw GamemodeEBNMIJSLs
        dw GamemodeECNMIJSLs
        dw GamemodeEDNMIJSLs
        dw GamemodeEENMIJSLs
        dw GamemodeEFNMIJSLs
        dw GamemodeF0NMIJSLs
        dw GamemodeF1NMIJSLs
        dw GamemodeF2NMIJSLs
        dw GamemodeF3NMIJSLs
        dw GamemodeF4NMIJSLs
        dw GamemodeF5NMIJSLs
        dw GamemodeF6NMIJSLs
        dw GamemodeF7NMIJSLs
        dw GamemodeF8NMIJSLs
        dw GamemodeF9NMIJSLs
        dw GamemodeFANMIJSLs
        dw GamemodeFBNMIJSLs
        dw GamemodeFCNMIJSLs
        dw GamemodeFDNMIJSLs
        dw GamemodeFENMIJSLs
        dw GamemodeFFNMIJSLs
endif


OverworldResourcePointers:
    dw Overworld0JSLs
    dw Overworld1JSLs
    dw Overworld2JSLs
    dw Overworld3JSLs
    dw Overworld4JSLs
    dw Overworld5JSLs
    dw Overworld6JSLs


if !UberLevelNMINormal
    NMIOverworldResourcePointers:
        dw Overworld0NMIJSLs
        dw Overworld1NMIJSLs
        dw Overworld2NMIJSLs
        dw Overworld3NMIJSLs
        dw Overworld4NMIJSLs
        dw Overworld5NMIJSLs
        dw Overworld6NMIJSLs
endif

