name: Deploy versioned Readme to Pages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Fetch all tags to access version history
      - name: Fetch tags
        run: git fetch --tags

      # Generate and deploy pages for each tag
      - name: Deploy for each tag
        run: |
          # versioned docs
          mkdir -p site
          for tag in $(git tag); do
            git checkout "$tag"
            if [ -d "./docs/baserom_readme/" ]; then
              mkdir -p "site/$tag"
              cp -R ./docs/baserom_readme/* "site/$tag/"
            else
              echo "No documentation for tag $tag."
            fi
          done
          # main docs
          git checkout "RHRv5"
          cp -R ./docs/baserom_readme/* site/

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
